export const Projects = [
  {
    id: 1,
    name: "Tic Tac Toe",
    img: "/Portafolio/img/project1.jpg",
    link: "https://sulkybug.github.io/Sulkybug.Tic-Tac-Toe.Game./",
    codeLink: "https://github.com/Sulkybug/Sulkybug.Tic-Tac-Toe.Game.",
  },
  {
    id: 2,
    name: "Wheater App",
    img: "/Portafolio/img/project2.jpg",
    link: "https://sulkybug.github.io/Sulkybug-Weather-app-/",
    codeLink: "https://github.com/Sulkybug/Sulkybug-Weather-app-",
  },
  {
    id: 3,
    name: "7 Segment Display",
    img: "/Portafolio/img/project3.jpg",
    link: "https://sulkybug.github.io/7-Segment-Display/",
    codeLink: "https://github.com/Sulkybug/7-Segment-Display",
  },
  {
    id: 4,
    name: "Product Website Concept ",
    img: "/Portafolio/img/project4.jpg",
    link: "https://sulkybug.github.io/monkeyFist-OnlineStore-Concept/",
    codeLink: "https://github.com/Sulkybug/monkeyFist-OnlineStore-Concept",
  },

  {
    id: 5,
    name: "Digital Watch & Chronometer",
    img: "/Portafolio/img/project5.jpg",
    link: "https://sulkybug.github.io/Digital-Watch-chronometer/",
    codeLink: "https://github.com/Sulkybug/Digital-Watch-chronometer-TS/",
  },
  {
    id: 6,
    name: "Mini Piano",
    img: "/Portafolio/img/project6.jpg",
    link: "https://sulkybug.github.io/Mini-Piano/",
    codeLink: "https://github.com/Sulkybug/Mini-Piano",
  },
  {
    id: 7,
    name: "Caesar Cipher ROT ALL",
    img: "/Portafolio/img/project7.jpg",
    link: "https://sulkybug.github.io/Codificador-Caesar-Cipher/",
    codeLink: "https://github.com/Sulkybug/Codificador-Caesar-Cipher",
  },
  {
    id: 8,
    name: "Converter",
    img: "/Portafolio/img/project8.jpg",
    link: "https://sulkybug.github.io/Converter/",
    codeLink: "https://github.com/Sulkybug/Converter",
  },
  {
    id: 9,
    name: "Bakery Website",
    img: "/Portafolio/img/project9.jpg",
    link: "https://sulkybug.github.io/ZeroPorcientoAzucar/",
    codeLink: "https://github.com/Sulkybug/ZeroPorcientoAzucar",
  },
  {
    id: 10,
    name: "List of Things to do",
    img: "/Portafolio/img/project10.jpg",
    link: "https://sulkybug.github.io/List-of-things-to-do/",
    codeLink: "https://github.com/Sulkybug/List-of-things-to-do",
  },
  {
    id: 11,
    name: "Roll The Dice",
    img: "/Portafolio/img/project11.jpg",
    link: "https://sulkybug.github.io/RollTheDice/",
    codeLink: "https://github.com/Sulkybug/RollTheDice",
  },
];
