export const Projects = [
  {
    id: 1,
    name: "Digital Watch & Chronometer",
    img: "/img/project1.jpg",
    link: "https://sulkybug.github.io/Digital-Watch-chronometer/",
    codeLink: "https://github.com/Sulkybug/Digital-Watch-chronometer",
  },
  {
    id: 2,
    name: "Tic Tac Toe",
    img: "/img/project2.jpg",
    link: "https://sulkybug.github.io/Sulkybug.Tic-Tac-Toe.Game./",
    codeLink: "https://github.com/Sulkybug/Sulkybug.Tic-Tac-Toe.Game.",
  },
  {
    id: 3,
    name: "Wheater App",
    img: "/img/project3.jpg",
    link: "https://sulkybug.github.io/Sulkybug-Weather-app-/",
    codeLink: "https://github.com/Sulkybug/Sulkybug-Weather-app-",
  },
  {
    id: 4,
    name: "7 Segment Display",
    img: "/img/project4.jpg",
    link: "https://sulkybug.github.io/Sulkybug-7-Segment-Display/",
    codeLink: "https://github.com/Sulkybug/Sulkybug-7-Segment-Display",
  },
  {
    id: 5,
    name: "Product Website Concept ",
    img: "/img/project5.jpg",
    link: "https://sulkybug.github.io/monkeyFist-OnlineStore-Concept/",
    codeLink: "https://github.com/Sulkybug/monkeyFist-OnlineStore-Concept",
  },
  {
    id: 6,
    name: "Mini Piano",
    img: "/img/project6.jpg",
    link: "https://sulkybug.github.io/Mini-Piano/",
    codeLink: "https://github.com/Sulkybug/Mini-Piano",
  },
  {
    id: 7,
    name: "Caesar Cipher ROT ALL",
    img: "/img/project7.jpg",
    link: "https://sulkybug.github.io/Sulkybug.CodificadorCaesarCipher/",
    codeLink: "https://github.com/Sulkybug/Sulkybug.CodificadorCaesarCipher",
  },
];
